schema-version = 1

[package]
title = "Kaylane TV"
version = "0.1.0"
id = "com.kaylanetv.browser"
icon = "@image/kaylane-tv.png"

[os.version]
min = "1.2"
target = "1.2"

[components]
[[components.interactive]]
id = "com.kaylanetv.browser.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
categories = ["com.amazon.category.main", "com.amazon.category.kepler.media"]
launch-type = "singleton"

[wants]
[[wants.service]]
id = "com.amazon.webview.renderer_service"

[[wants.service]]
id = "com.amazon.inputmethod.service"

[[wants.service]]
id = "com.amazon.inputd.service"

[[wants.service]]
id = "com.amazon.network.service"

[[wants.service]]
id = "com.amazon.mediametrics.service"

[[wants.service]]
id = "com.amazon.media.server"

[[wants.service]]
id = "com.amazon.media.playersession.service"

[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
id = "com.amazon.audio.stream"

[[wants.service]]
id = "com.amazon.audio.control"

[[wants.service]]
id = "com.amazon.audio.system"

[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[[wants.privilege]]
id = "com.amazon.devconf.privilege.accessibility"

[needs]
[[needs.module]]
id = "/com.amazon.vega.os@IVega_1_2"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"

[[extras]]
key = "interface.provider"
component-id = "com.kaylanetv.browser.main"

[extras.value.application]
[[extras.value.application.interface]]
interface_name = "com.amazon.kepler.media.IMediaPlaybackServer"
command_options = ["SkipForward", "SkipBackward"]
